
spring.application.name=SimpleLibraryGame
book.image.path=${BOOK_IMAGE_PATH:/svr/books_img}
jwt.token.secret=${JWT_TOKEN_SECRET:my-token-secret}

spring.config.import=optional:file:.env[.properties]
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}

spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.format_sql=true
